pipeline {
    agent any

    environment {
        IMAGE_NAME = "yourdockerusername/jenkins-demo-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/your-repo/jenkins-demo.git'
            }
        }

        stage('Build App') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'Docker',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh '''
                ssh ubuntu@13.232.156.31 << EOF
                docker pull yourdockerusername/jenkins-demo-app
                docker stop demo || true
                docker rm demo || true
                docker run -d -p 80:3000 --name demo yourdockerusername/jenkins-demo-app
                EOF
                '''
            }
        }
    }
}